/**
 * @license
 * lodash 4.2.0 (Custom Build) lodash.com/license | Underscore.js 1.8.3 underscorejs.org/LICENSE
 * Build: `lodash include="forEach,map,filter,take,takeRight,value,orderBy,get,set"`
 */
;(function(){function t(t,e){return t.set(e[0],e[1]),t}function e(t,e){return t.add(e),t}function r(t,e,r){switch(r.length){case 0:return t.call(e);case 1:return t.call(e,r[0]);case 2:return t.call(e,r[0],r[1]);case 3:return t.call(e,r[0],r[1],r[2])}return t.apply(e,r)}function n(t,e){for(var r=-1,n=t.length;++r<n&&false!==e(t[r],r,t););return t}function o(t,e){for(var r=-1,n=t.length,o=-1,u=[];++r<n;){var i=t[r];e(i,r,t)&&(u[++o]=i)}return u}function u(t,e){for(var r=-1,n=t.length,o=Array(n);++r<n;)o[r]=e(t[r],r,t);
return o}function i(t,e){for(var r=-1,n=e.length,o=t.length;++r<n;)t[o+r]=e[r];return t}function a(t,e,r){for(var n=-1,o=t.length;++n<o;)r=e(r,t[n],n,t);return r}function c(t,e){for(var r=-1,n=t.length;++r<n;)if(e(t[r],r,t))return true;return false}function f(t,e){var r=t.length;for(t.sort(e);r--;)t[r]=t[r].c;return t}function _(t,e){return u(e,function(e){return[e,t[e]]})}function s(t,e){return u(e,function(e){return t[e]})}function l(t){return t&&t.Object===Object?t:null}function p(t){var e=false;if(null!=t&&typeof t.toString!="function")try{
e=!!(t+"")}catch(r){}return e}function h(t,e){return t=typeof t=="number"||ce.test(t)?+t:-1,t>-1&&0==t%1&&(null==e?9007199254740991:e)>t}function y(t){var e=-1,r=Array(t.size);return t.forEach(function(t,n){r[++e]=[n,t]}),r}function v(t){var e=-1,r=Array(t.size);return t.forEach(function(t){r[++e]=t}),r}function b(t){if(Et(t)&&!ir(t)&&!(t instanceof j)){if(t instanceof d)return t;if(xe.call(t,"__wrapped__"))return yt(t)}return new d(t)}function g(){}function d(t,e){this.__wrapped__=t,this.__actions__=[],
this.__chain__=!!e,this.__index__=0,this.__values__=Kt}function j(t){this.__wrapped__=t,this.__actions__=[],this.__dir__=1,this.__filtered__=false,this.__iteratees__=[],this.__takeCount__=4294967295,this.__views__=[]}function w(){}function m(t){var e=-1,r=t?t.length:0;for(this.clear();++e<r;){var n=t[e];this.set(n[0],n[1])}}function A(t){var e=-1,r=t?t.length:0;for(this.clear();++e<r;){var n=t[e];this.set(n[0],n[1])}}function k(t,e){var r=x(t,e);return 0>r?false:(r==t.length-1?t.pop():Ce.call(t,r,1),true);
}function O(t,e){var r=x(t,e);return 0>r?Kt:t[r][1]}function x(t,e){for(var r=t.length;r--;)if(At(t[r][0],e))return r;return-1}function S(t,e,r){var n=x(t,e);0>n?t.push([e,r]):t[n][1]=r}function R(t,e,r){var n=t[e];(!At(n,r)||At(n,ke[e])&&!xe.call(t,e)||r===Kt&&!(e in t))&&(t[e]=r)}function $(t,e){var r;return(r=t)&&(r=Dt(e),r=X(e,r,t)),r}function E(t,e,r,o,u,i){var a;if(r&&(a=u?r(t,o,u,i):r(t)),a!==Kt)return a;if(!$t(t))return t;if(o=ir(t)){if(a=ct(t),!e)return Q(t,a)}else{var c=at(t),f="[object Function]"==c||"[object GeneratorFunction]"==c;
if("[object Object]"!=c&&"[object Arguments]"!=c&&(!f||u))return pe[c]?_t(t,c,e):u?t:{};if(p(t))return u?t:{};if(a=ft(f?{}:t),!e)return Y(t,$(a,t))}return i||(i=new A),(u=i.get(t))?u:(i.set(t,a),(o?n:M)(t,function(n,o){R(a,o,E(n,e,r,o,t,i))}),o?a:Y(t,a))}function I(t,e){var r=[];return Ye(t,function(t,n,o){e(t,n,o)&&r.push(t)}),r}function F(t,e,r,n){n||(n=[]);for(var o=-1,u=t.length;++o<u;){var a=t[o];xt(a)&&(r||ir(a)||kt(a))?e?F(a,e,r,n):i(n,a):r||(n[n.length]=a)}return n}function M(t,e){return t&&Ze(t,e,Dt);
}function U(t,e){return o(e,function(e){return St(t[e])})}function C(t,e){e=st(e,t)?[e+""]:V(e);for(var r=0,n=e.length;null!=t&&n>r;)t=t[e[r++]];return r&&r==n?t:Kt}function N(t,e){return xe.call(t,e)||typeof t=="object"&&e in t&&null===Ie(t)}function B(t,e,r,n,o){if(t===e)t=true;else if(null==t||null==e||!$t(t)&&!Et(e))t=t!==t&&e!==e;else t:{var u=ir(t),i=ir(e),a="[object Array]",c="[object Array]";u||(a=at(t),"[object Arguments]"==a?a="[object Object]":"[object Object]"!=a&&(u=Ut(t))),i||(c=at(e),
"[object Arguments]"==c?c="[object Object]":"[object Object]"!=c&&Ut(e));var f="[object Object]"==a&&!p(t),i="[object Object]"==c&&!p(e),c=a==c;if(!c||u||f){if(!(2&n)&&(a=f&&xe.call(t,"__wrapped__"),i=i&&xe.call(e,"__wrapped__"),a||i)){t=B(a?t.value():t,i?e.value():e,r,n,o);break t}c?(o||(o=new A),t=(u?et:nt)(t,e,B,r,n,o)):t=false}else t=rt(t,e,a,B,r,n)}return t}function L(t,e){var r=e.length,n=r;if(null==t)return!n;for(t=Object(t);r--;){var o=e[r];if(o[2]?o[1]!==t[o[0]]:!(o[0]in t))return false}for(;++r<n;){
var o=e[r],u=o[0],i=t[u],a=o[1];if(o[2]){if(i===Kt&&!(u in t))return false}else if(o=new A,u=Kt,u===Kt?!B(a,i,void 0,3,o):!u)return false}return true}function W(t){var e=typeof t;return"function"==e?t:null==t?Gt:"object"==e?ir(t)?P(t[0],t[1]):D(t):Ht(t)}function z(t,e){var r=-1,n=Ot(t)?Array(t.length):[];return Ye(t,function(t,o,u){n[++r]=e(t,o,u)}),n}function D(t){var e=ut(t);if(1==e.length&&e[0][2]){var r=e[0][0],n=e[0][1];return function(t){return null==t?false:t[r]===n&&(n!==Kt||r in Object(t))}}return function(r){
return r===t||L(r,e)}}function P(t,e){return function(r){var n=Wt(r,t);return n===Kt&&n===e?zt(r,t):B(e,n,Kt,3)}}function T(t,e,r){var n=-1,o=ot();return e=u(e.length?e:Array(1),function(t){return o(t)}),t=z(t,function(t){return{a:u(e,function(e){return e(t)}),b:++n,c:t}}),f(t,function(t,e){var n;t:{n=-1;for(var o=t.a,u=e.a,i=o.length,a=r.length;++n<i;){var c;e:{c=o[n];var f=u[n];if(c!==f){var _=null===c,s=c===Kt,l=c===c,p=null===f,h=f===Kt,y=f===f;if(c>f&&!p||!l||_&&!h&&y||s&&y){c=1;break e}if(f>c&&!_||!y||p&&!s&&l||h&&l){
c=-1;break e}}c=0}if(c){n=a>n?c*("desc"==r[n]?-1:1):c;break t}}n=t.b-e.b}return n})}function G(t){return function(e){return null==e?Kt:e[t]}}function q(t){return function(e){return C(e,t)}}function J(t,e,r){var n=-1,o=t.length;for(0>e&&(e=-e>o?0:o+e),r=r>o?o:r,0>r&&(r+=o),o=e>r?0:r-e>>>0,e>>>=0,r=Array(o);++n<o;)r[n]=t[n+e];return r}function V(t){return ir(t)?t:ht(t)}function H(t,e){var r=t;return r instanceof j&&(r=r.value()),a(e,function(t,e){return e.func.apply(e.thisArg,i([t],e.args))},r)}function K(t){
var e=new t.constructor(t.byteLength);return new Ee(e).set(new Ee(t)),e}function Q(t,e){var r=-1,n=t.length;for(e||(e=Array(n));++r<n;)e[r]=t[r];return e}function X(t,e,r){r||(r={});for(var n=-1,o=e.length;++n<o;){var u=e[n];R(r,u,t[u])}return r}function Y(t,e){var r=nr(t);return X(t,r,e)}function Z(t){return function(){var e=arguments;switch(e.length){case 0:return new t;case 1:return new t(e[0]);case 2:return new t(e[0],e[1]);case 3:return new t(e[0],e[1],e[2]);case 4:return new t(e[0],e[1],e[2],e[3]);
case 5:return new t(e[0],e[1],e[2],e[3],e[4]);case 6:return new t(e[0],e[1],e[2],e[3],e[4],e[5]);case 7:return new t(e[0],e[1],e[2],e[3],e[4],e[5],e[6])}var r=Xe(t.prototype),e=t.apply(r,e);return $t(e)?e:r}}function tt(t,e,r,n,o,u,i,a,c,f){function _(){for(var w=arguments.length,m=w,A=Array(w);m--;)A[m]=arguments[m];if(n){for(var m=A,k=o.length,O=-1,A=Be(m.length-k,0),x=-1,S=n.length,R=Array(S+A);++x<S;)R[x]=n[x];for(;++O<k;)R[o[O]]=m[O];for(;A--;)R[x++]=m[O++];A=R}if(u){for(var m=A,k=-1,O=i.length,A=-1,$=Be(m.length-O,0),x=-1,S=u.length,R=Array($+S);++A<$;)R[A]=m[A];
for($=A;++x<S;)R[$+x]=u[x];for(;++k<O;)R[$+i[k]]=m[A++];A=R}if(y||v){for(m=_.placeholder,O=A,x=-1,S=O.length,R=-1,k=[];++x<S;)O[x]===m&&(O[x]="__lodash_placeholder__",k[++R]=x);if(w-=k.length,f>w){O=e,w=f-w,x=8&O,S=a?Q(a):Kt,R=x?k:Kt,k=x?Kt:k,$=x?A:Kt,A=x?Kt:A,O=(O|(x?32:64))&~(x?64:32),4&O||(O&=-4),w=[t,O,r,$,R,A,k,S,c,w],k=tt.apply(Kt,w);t:for(O=t.name+"",A=Qe[O],x=xe.call(Qe,O)?A.length:0;x--;)if(S=A[x],R=S.func,null==R||R==t){O=S.name;break t}return A=b[O],typeof A=="function"&&O in j.prototype?t===A?O=true:(O=er(A),
O=!!O&&t===O[0]):O=false,O&&or(k,w),k.placeholder=m,k}}if(m=l?r:this,w=p?m[t]:t,a){for(k=A,O=k.length,A=Le(a.length,O),x=Q(k);A--;)S=a[A],k[A]=h(S,O)?x[S]:Kt;A=k}else g&&A.length>1&&A.reverse();return s&&A.length>c&&(A.length=c),this&&this!==me&&this instanceof _&&(w=d||Z(w)),w.apply(m,A)}var s=128&e,l=1&e,p=2&e,y=8&e,v=16&e,g=512&e,d=p?Kt:Z(t);return _}function et(t,e,r,n,o,u){var i=-1,a=2&o,f=1&o,_=t.length,s=e.length;if(!(_==s||a&&s>_))return false;if(s=u.get(t))return s==e;for(s=true,u.set(t,e);++i<_;){
var l=t[i],p=e[i];if(n)var h=a?n(p,l,i,e,t,u):n(l,p,i,t,e,u);if(h!==Kt){if(h)continue;s=false;break}if(f){if(!c(e,function(t){return l===t||r(l,t,n,o,u)})){s=false;break}}else if(l!==p&&!r(l,p,n,o,u)){s=false;break}}return u["delete"](t),s}function rt(t,e,r,n,o,u){switch(r){case"[object ArrayBuffer]":if(t.byteLength!=e.byteLength||!n(new Ee(t),new Ee(e)))break;return true;case"[object Boolean]":case"[object Date]":return+t==+e;case"[object Error]":return t.name==e.name&&t.message==e.message;case"[object Number]":
return t!=+t?e!=+e:t==+e;case"[object RegExp]":case"[object String]":return t==e+"";case"[object Map]":var i=y;case"[object Set]":return i||(i=v),(2&u||t.size==e.size)&&n(i(t),i(e),o,1|u);case"[object Symbol]":return!!$e&&He.call(t)==He.call(e)}return false}function nt(t,e,r,n,o,u){var i=2&o,a=Dt(t),c=a.length,f=Dt(e).length;if(c!=f&&!i)return false;for(var _=c;_--;){var s=a[_];if(!(i?s in e:N(e,s)))return false}if(f=u.get(t))return f==e;f=true,u.set(t,e);for(var l=i;++_<c;){var s=a[_],p=t[s],h=e[s];if(n)var y=i?n(h,p,s,e,t,u):n(p,h,s,t,e,u);
if(y===Kt?p!==h&&!r(p,h,n,o,u):!y){f=false;break}l||(l="constructor"==s)}return f&&!l&&(r=t.constructor,n=e.constructor,r!=n&&"constructor"in t&&"constructor"in e&&!(typeof r=="function"&&r instanceof r&&typeof n=="function"&&n instanceof n)&&(f=false)),u["delete"](t),f}function ot(){var t=b.iteratee||qt,t=t===qt?W:t;return arguments.length?t(arguments[0],arguments[1]):t}function ut(t){t=Pt(t);for(var e=t.length;e--;){var r=t[e][1];t[e][2]=r===r&&!$t(r)}return t}function it(t,e){var r=null==t?Kt:t[e];return It(r)?r:Kt;
}function at(t){return Se.call(t)}function ct(t){var e=t.length,r=t.constructor(e);return e&&"string"==typeof t[0]&&xe.call(t,"index")&&(r.index=t.index,r.input=t.input),r}function ft(t){return pt(t)?{}:(t=t.constructor,Xe(St(t)?t.prototype:Kt))}function _t(r,n,o){var u=r.constructor;switch(n){case"[object ArrayBuffer]":return K(r);case"[object Boolean]":case"[object Date]":return new u(+r);case"[object Float32Array]":case"[object Float64Array]":case"[object Int8Array]":case"[object Int16Array]":
case"[object Int32Array]":case"[object Uint8Array]":case"[object Uint8ClampedArray]":case"[object Uint16Array]":case"[object Uint32Array]":return n=r.buffer,new r.constructor(o?K(n):n,r.byteOffset,r.length);case"[object Map]":return o=r.constructor,a(y(r),t,new o);case"[object Number]":case"[object String]":return new u(r);case"[object RegExp]":return o=new r.constructor(r.source,ne.exec(r)),o.lastIndex=r.lastIndex,o;case"[object Set]":return o=r.constructor,a(v(r),e,new o);case"[object Symbol]":
return $e?Object(He.call(r)):{}}}function st(t,e){return typeof t=="number"?true:!ir(t)&&(Zt.test(t)||!Yt.test(t)||null!=e&&t in Object(e))}function lt(t){var e=typeof t;return"number"==e||"boolean"==e||"string"==e&&"__proto__"!==t||null==t}function pt(t){var e=t&&t.constructor;return t===(typeof e=="function"&&e.prototype||ke)}function ht(t){var e=[];return Lt(t).replace(te,function(t,r,n,o){e.push(n?o.replace(re,"$1"):r||t)}),e}function yt(t){if(t instanceof j)return t.clone();var e=new d(t.__wrapped__,t.__chain__);
return e.__actions__=Q(t.__actions__),e.__index__=t.__index__,e.__values__=t.__values__,e}function vt(t){var e=t?t.length:0;return e?t[e-1]:Kt}function bt(t){return t?We.call(t):t}function gt(t){return t=b(t),t.__chain__=true,t}function dt(t,e){return e(t)}function jt(){return this}function wt(t,e){return typeof e=="function"&&ir(t)?n(t,e):Ye(t,typeof e=="function"?e:Gt)}function mt(t,e){if(typeof t!="function")throw new TypeError("Expected a function");return e=Be(e===Kt?t.length-1:Nt(e),0),function(){
for(var n=arguments,o=-1,u=Be(n.length-e,0),i=Array(u);++o<u;)i[o]=n[e+o];switch(e){case 0:return t.call(this,i);case 1:return t.call(this,n[0],i);case 2:return t.call(this,n[0],n[1],i)}for(u=Array(e+1),o=-1;++o<e;)u[o]=n[o];return u[e]=i,r(t,this,u)}}function At(t,e){return t===e||t!==t&&e!==e}function kt(t){return xt(t)&&xe.call(t,"callee")&&(!Ue.call(t,"callee")||"[object Arguments]"==Se.call(t))}function Ot(t){return null!=t&&!(typeof t=="function"&&St(t))&&Rt(rr(t))}function xt(t){return Et(t)&&Ot(t);
}function St(t){return t=$t(t)?Se.call(t):"","[object Function]"==t||"[object GeneratorFunction]"==t}function Rt(t){return typeof t=="number"&&t>-1&&0==t%1&&9007199254740991>=t}function $t(t){var e=typeof t;return!!t&&("object"==e||"function"==e)}function Et(t){return!!t&&typeof t=="object"}function It(t){return null==t?false:St(t)?Re.test(Oe.call(t)):Et(t)&&(p(t)?Re:ie).test(t)}function Ft(t){return typeof t=="string"||!ir(t)&&Et(t)&&"[object String]"==Se.call(t)}function Mt(t){return typeof t=="symbol"||Et(t)&&"[object Symbol]"==Se.call(t);
}function Ut(t){return Et(t)&&Rt(t.length)&&!!le[Se.call(t)]}function Ct(t){if(!t)return[];if(Ot(t))return Ft(t)?t.match(se):Q(t);if(Me&&t[Me]){t=t[Me]();for(var e,r=[];!(e=t.next()).done;)r.push(e.value);return r}return e=at(t),("[object Map]"==e?y:"[object Set]"==e?v:Tt)(t)}function Nt(t){if(!t)return 0===t?t:0;if(t=Bt(t),t===Qt||t===-Qt)return 1.7976931348623157e308*(0>t?-1:1);var e=t%1;return t===t?e?t-e:t:0}function Bt(t){if($t(t)&&(t=St(t.valueOf)?t.valueOf():t,t=$t(t)?t+"":t),typeof t!="string")return 0===t?t:+t;
t=t.replace(ee,"");var e=ue.test(t);return e||ae.test(t)?ye(t.slice(2),e?2:8):oe.test(t)?Xt:+t}function Lt(t){if(typeof t=="string")return t;if(null==t)return"";if(Mt(t))return $e?Ke.call(t):"";var e=t+"";return"0"==e&&1/t==-Qt?"-0":e}function Wt(t,e,r){return t=null==t?Kt:C(t,e),t===Kt?r:t}function zt(t,e){var r;r=t;var n=e;if(null==r)r=false;else{var o=n in Object(r);o||st(n)||(n=V(n),r=1==n.length?r:Wt(r,J(n,0,-1)),null!=r&&(n=vt(n),o=n in Object(r)));var u=r?r.length:Kt;r=o||!!u&&Rt(u)&&h(n,u)&&(ir(r)||Ft(r)||kt(r));
}return r}function Dt(t){var e=pt(t);if(!e&&!Ot(t))return Ne(Object(t));var r,n=t?t.length:Kt;if(Rt(n)&&(ir(t)||Ft(t)||kt(t))){r=String;for(var o=-1,u=Array(n);++o<n;)u[o]=r(o);n=u}else n=null;r=n,n=!!r,r=r||[];var i,o=r.length;for(i in t)!N(t,i)||n&&("length"==i||h(i,o))||e&&"constructor"==i||r.push(i);return r}function Pt(t){return _(t,Dt(t))}function Tt(t){return t?s(t,Dt(t)):[]}function Gt(t){return t}function qt(t){return W(typeof t=="function"?t:E(t,true))}function Jt(t,e,r){var o=Dt(e),u=U(e,o);
null!=r||$t(e)&&(u.length||!o.length)||(r=e,e=t,t=this,u=U(e,Dt(e)));var a=$t(r)&&"chain"in r?r.chain:true,c=St(t);return n(u,function(r){var n=e[r];t[r]=n,c&&(t.prototype[r]=function(){var e=this.__chain__;if(a||e){var r=t(this.__wrapped__);return(r.__actions__=Q(this.__actions__)).push({func:n,args:arguments,thisArg:t}),r.__chain__=e,r}return n.apply(t,i([this.value()],arguments))})}),t}function Vt(){}function Ht(t){return st(t)?G(t):q(t)}var Kt,Qt=1/0,Xt=NaN,Yt=/\.|\[(?:[^[\]]*|(["'])(?:(?!\1)[^\\]|\\.)*?\1)\]/,Zt=/^\w*$/,te=/[^.[\]]+|\[(?:(-?\d+(?:\.\d+)?)|(["'])((?:(?!\2)[^\\]|\\.)*?)\2)\]/g,ee=/^\s+|\s+$/g,re=/\\(\\)?/g,ne=/\w*$/,oe=/^[-+]0x[0-9a-f]+$/i,ue=/^0b[01]+$/i,ie=/^\[object .+?Constructor\]$/,ae=/^0o[0-7]+$/i,ce=/^(?:0|[1-9]\d*)$/,fe="[\\ufe0e\\ufe0f]?(?:[\\u0300-\\u036f\\ufe20-\\ufe23\\u20d0-\\u20f0]|\\ud83c[\\udffb-\\udfff])?(?:\\u200d(?:[^\\ud800-\\udfff]|(?:\\ud83c[\\udde6-\\uddff]){2}|[\\ud800-\\udbff][\\udc00-\\udfff])[\\ufe0e\\ufe0f]?(?:[\\u0300-\\u036f\\ufe20-\\ufe23\\u20d0-\\u20f0]|\\ud83c[\\udffb-\\udfff])?)*",_e="(?:[^\\ud800-\\udfff][\\u0300-\\u036f\\ufe20-\\ufe23\\u20d0-\\u20f0]?|[\\u0300-\\u036f\\ufe20-\\ufe23\\u20d0-\\u20f0]|(?:\\ud83c[\\udde6-\\uddff]){2}|[\\ud800-\\udbff][\\udc00-\\udfff]|[\\ud800-\\udfff])",se=RegExp("\\ud83c[\\udffb-\\udfff](?=\\ud83c[\\udffb-\\udfff])|"+_e+fe,"g"),le={};
le["[object Float32Array]"]=le["[object Float64Array]"]=le["[object Int8Array]"]=le["[object Int16Array]"]=le["[object Int32Array]"]=le["[object Uint8Array]"]=le["[object Uint8ClampedArray]"]=le["[object Uint16Array]"]=le["[object Uint32Array]"]=true,le["[object Arguments]"]=le["[object Array]"]=le["[object ArrayBuffer]"]=le["[object Boolean]"]=le["[object Date]"]=le["[object Error]"]=le["[object Function]"]=le["[object Map]"]=le["[object Number]"]=le["[object Object]"]=le["[object RegExp]"]=le["[object Set]"]=le["[object String]"]=le["[object WeakMap]"]=false;
var pe={};pe["[object Arguments]"]=pe["[object Array]"]=pe["[object ArrayBuffer]"]=pe["[object Boolean]"]=pe["[object Date]"]=pe["[object Float32Array]"]=pe["[object Float64Array]"]=pe["[object Int8Array]"]=pe["[object Int16Array]"]=pe["[object Int32Array]"]=pe["[object Map]"]=pe["[object Number]"]=pe["[object Object]"]=pe["[object RegExp]"]=pe["[object Set]"]=pe["[object String]"]=pe["[object Symbol]"]=pe["[object Uint8Array]"]=pe["[object Uint8ClampedArray]"]=pe["[object Uint16Array]"]=pe["[object Uint32Array]"]=true,
pe["[object Error]"]=pe["[object Function]"]=pe["[object WeakMap]"]=false;var he={"function":true,object:true},ye=parseInt,ve=he[typeof exports]&&exports&&!exports.nodeType?exports:null,be=he[typeof module]&&module&&!module.nodeType?module:null,ge=l(he[typeof self]&&self),de=l(he[typeof window]&&window),je=be&&be.exports===ve?ve:null,we=l(he[typeof this]&&this),me=l(ve&&be&&typeof global=="object"&&global)||de!==(we&&we.window)&&de||ge||we||Function("return this")(),Ae=Array.prototype,ke=Object.prototype,Oe=Function.prototype.toString,xe=ke.hasOwnProperty,Se=ke.toString,Re=RegExp("^"+Oe.call(xe).replace(/[\\^$.*+?()[\]{}|]/g,"\\$&").replace(/hasOwnProperty|(function).*?(?=\\\()| for .+?(?=\\\])/g,"$1.*?")+"$"),$e=me.Symbol,Ee=me.Uint8Array,Ie=Object.getPrototypeOf,Fe=Object.getOwnPropertySymbols,Me=typeof(Me=$e&&$e.iterator)=="symbol"?Me:Kt,Ue=ke.propertyIsEnumerable,Ce=Ae.splice,Ne=Object.keys,Be=Math.max,Le=Math.min,We=Ae.reverse,ze=it(me,"Map"),De=it(me,"Set"),Pe=it(me,"WeakMap"),Te=it(Object,"create"),Ge=Pe&&new Pe,qe=ze?Oe.call(ze):"",Je=De?Oe.call(De):"",Ve=$e?$e.prototype:Kt,He=$e?Ve.valueOf:Kt,Ke=$e?Ve.toString:Kt,Qe={},Xe=function(){
function t(){}return function(e){if($t(e)){t.prototype=e;var r=new t;t.prototype=Kt}return r||{}}}(),Ye=function(t,e){return function(r,n){if(null==r)return r;if(!Ot(r))return t(r,n);for(var o=r.length,u=e?o:-1,i=Object(r);(e?u--:++u<o)&&false!==n(i[u],u,i););return r}}(M),Ze=function(t){return function(e,r,n){var o=-1,u=Object(e);n=n(e);for(var i=n.length;i--;){var a=n[t?i:++o];if(false===r(u[a],a,u))break}return e}}(),tr=Ge?function(t,e){return Ge.set(t,e),t}:Gt,er=Ge?function(t){return Ge.get(t)}:Vt,rr=G("length"),nr=Fe||function(){
return[]};(ze&&"[object Map]"!=at(new ze)||De&&"[object Set]"!=at(new De))&&(at=function(t){var e=Se.call(t);if(t="[object Object]"==e?t.constructor:null,t=typeof t=="function"?Oe.call(t):""){if(t==qe)return"[object Map]";if(t==Je)return"[object Set]"}return e});var or=function(){var t=0,e=0;return function(r,n){var o=ur(),u=16-(o-e);if(e=o,u>0){if(150<=++t)return r}else t=0;return tr(r,n)}}();mt(function(t){function e(e){for(var r=t,n=-1,o=null==e,u=r.length,i=Array(u);++n<u;)i[n]=o?Kt:Wt(e,r[n]);
return i}t=F(t);var r=t.length,n=r?t[0]:0,o=this.__wrapped__;return 1>=r&&!this.__actions__.length&&o instanceof j&&h(n)?(o=o.slice(n,+n+(r?1:0)),o.__actions__.push({func:dt,args:[e],thisArg:Kt}),new d(o,this.__chain__).thru(function(t){return r&&!t.length&&t.push(Kt),t})):this.thru(e)});var ur=Date.now,ir=Array.isArray;b.prototype=g.prototype,d.prototype=Xe(g.prototype),d.prototype.constructor=d,j.prototype=Xe(g.prototype),j.prototype.constructor=j,w.prototype=Te?Te(null):ke,m.prototype.clear=function(){
this.__data__={hash:new w,map:ze?new ze:[],string:new w}},m.prototype["delete"]=function(t){var e=this.__data__;return lt(t)?(e=typeof t=="string"?e.string:e.hash,t=(Te?e[t]!==Kt:xe.call(e,t))&&delete e[t]):t=ze?e.map["delete"](t):k(e.map,t),t},m.prototype.get=function(t){var e=this.__data__;return lt(t)?(e=typeof t=="string"?e.string:e.hash,Te?(t=e[t],t="__lodash_hash_undefined__"===t?Kt:t):t=xe.call(e,t)?e[t]:Kt):t=ze?e.map.get(t):O(e.map,t),t},m.prototype.has=function(t){var e=this.__data__;return lt(t)?(e=typeof t=="string"?e.string:e.hash,
t=Te?e[t]!==Kt:xe.call(e,t)):t=ze?e.map.has(t):-1<x(e.map,t),t},m.prototype.set=function(t,e){var r=this.__data__;return lt(t)?(typeof t=="string"?r.string:r.hash)[t]=Te&&e===Kt?"__lodash_hash_undefined__":e:ze?r.map.set(t,e):S(r.map,t,e),this},A.prototype.clear=function(){this.__data__={array:[],map:null}},A.prototype["delete"]=function(t){var e=this.__data__,r=e.array;return r?k(r,t):e.map["delete"](t)},A.prototype.get=function(t){var e=this.__data__,r=e.array;return r?O(r,t):e.map.get(t)},A.prototype.has=function(t){
var e=this.__data__,r=e.array;return r?-1<x(r,t):e.map.has(t)},A.prototype.set=function(t,e){var r=this.__data__,n=r.array;return n&&(199>n.length?S(n,t,e):(r.array=null,r.map=new m(n))),(r=r.map)&&r.set(t,e),this},b.chain=gt,b.filter=function(t,e){return(ir(t)?o:I)(t,ot(e,3))},b.iteratee=qt,b.keys=Dt,b.map=function(t,e){return(ir(t)?u:z)(t,ot(e,3))},b.mixin=Jt,b.orderBy=function(t,e,r,n){return null==t?[]:(ir(e)||(e=null==e?[]:[e]),r=n?Kt:r,ir(r)||(r=null==r?[]:[r]),T(t,e,r))},b.property=Ht,b.rest=mt,
b.reverse=bt,b.set=function(t,e,r){if(null!=t){e=st(e,t)?[e+""]:V(e);for(var n=-1,o=e.length,u=o-1,i=t;null!=i&&++n<o;){var a=e[n];if($t(i)){var c=r;if(n!=u){var f=i[a],c=Kt;c===Kt&&(c=null==f?h(e[n+1])?[]:{}:f)}R(i,a,c)}i=i[a]}}return t},b.take=function(t,e,r){return t&&t.length?(e=r||e===Kt?1:Nt(e),J(t,0,0>e?0:e)):[]},b.takeRight=function(t,e,r){var n=t?t.length:0;return n?(e=r||e===Kt?1:Nt(e),e=n-e,J(t,0>e?0:e,n)):[]},b.tap=function(t,e){return e(t),t},b.thru=dt,b.toArray=Ct,b.toPairs=Pt,b.values=Tt,
Jt(b,b),b.eq=At,b.forEach=wt,b.get=Wt,b.hasIn=zt,b.identity=Gt,b.isArguments=kt,b.isArray=ir,b.isArrayLike=Ot,b.isArrayLikeObject=xt,b.isFunction=St,b.isLength=Rt,b.isNative=It,b.isObject=$t,b.isObjectLike=Et,b.isString=Ft,b.isSymbol=Mt,b.isTypedArray=Ut,b.last=vt,b.noop=Vt,b.now=ur,b.toInteger=Nt,b.toNumber=Bt,b.toString=Lt,b.each=wt,Jt(b,function(){var t={};return M(b,function(e,r){xe.call(b.prototype,r)||(t[r]=e)}),t}(),{chain:false}),b.VERSION="4.2.0",n(["drop","take"],function(t,e){j.prototype[t]=function(r){
var n=this.__filtered__;if(n&&!e)return new j(this);r=r===Kt?1:Be(Nt(r),0);var o=this.clone();return n?o.__takeCount__=Le(r,o.__takeCount__):o.__views__.push({size:Le(r,4294967295),type:t+(0>o.__dir__?"Right":"")}),o},j.prototype[t+"Right"]=function(e){return this.reverse()[t](e).reverse()}}),n(["filter","map","takeWhile"],function(t,e){var r=e+1,n=1==r||3==r;j.prototype[t]=function(t){var e=this.clone();return e.__iteratees__.push({iteratee:ot(t,3),type:r}),e.__filtered__=e.__filtered__||n,e}}),
n(["head","last"],function(t,e){var r="take"+(e?"Right":"");j.prototype[t]=function(){return this[r](1).value()[0]}}),n(["initial","tail"],function(t,e){var r="drop"+(e?"":"Right");j.prototype[t]=function(){return this.__filtered__?new j(this):this[r](1)}}),j.prototype.compact=function(){return this.filter(Gt)},j.prototype.find=function(t){return this.filter(t).head()},j.prototype.findLast=function(t){return this.reverse().find(t)},j.prototype.invokeMap=mt(function(t,e){return typeof t=="function"?new j(this):this.map(function(n){
var o=t;return st(o,n)||(o=V(o),n=1==o.length?n:Wt(n,J(o,0,-1)),o=vt(o)),o=null==n?n:n[o],null==o?Kt:r(o,n,e)})}),j.prototype.reject=function(t){return t=ot(t,3),this.filter(function(e){return!t(e)})},j.prototype.slice=function(t,e){t=Nt(t);var r=this;return r.__filtered__&&(t>0||0>e)?new j(r):(0>t?r=r.takeRight(-t):t&&(r=r.drop(t)),e!==Kt&&(e=Nt(e),r=0>e?r.dropRight(-e):r.take(e-t)),r)},j.prototype.takeRightWhile=function(t){return this.reverse().takeWhile(t).reverse()},j.prototype.toArray=function(){
return this.take(4294967295)},M(j.prototype,function(t,e){var r=/^(?:filter|find|map|reject)|While$/.test(e),n=/^(?:head|last)$/.test(e),o=b[n?"take"+("last"==e?"Right":""):e],u=n||/^find/.test(e);o&&(b.prototype[e]=function(){function e(t){return t=o.apply(b,i([t],c)),n&&l?t[0]:t}var a=this.__wrapped__,c=n?[1]:arguments,f=a instanceof j,_=c[0],s=f||ir(a);s&&r&&typeof _=="function"&&1!=_.length&&(f=s=false);var l=this.__chain__,p=!!this.__actions__.length,_=u&&!l,f=f&&!p;return!u&&s?(a=f?a:new j(this),
a=t.apply(a,c),a.__actions__.push({func:dt,args:[e],thisArg:Kt}),new d(a,l)):_&&f?t.apply(this,c):(a=this.thru(e),_?n?a.value()[0]:a.value():a)})}),n("pop push shift sort splice unshift".split(" "),function(t){var e=Ae[t],r=/^(?:push|sort|unshift)$/.test(t)?"tap":"thru",n=/^(?:pop|shift)$/.test(t);b.prototype[t]=function(){var t=arguments;return n&&!this.__chain__?e.apply(this.value(),t):this[r](function(r){return e.apply(r,t)})}}),M(j.prototype,function(t,e){var r=b[e];if(r){var n=r.name+"";(Qe[n]||(Qe[n]=[])).push({
name:e,func:r})}}),Qe[tt(Kt,2).name]=[{name:"wrapper",func:Kt}],j.prototype.clone=function(){var t=new j(this.__wrapped__);return t.__actions__=Q(this.__actions__),t.__dir__=this.__dir__,t.__filtered__=this.__filtered__,t.__iteratees__=Q(this.__iteratees__),t.__takeCount__=this.__takeCount__,t.__views__=Q(this.__views__),t},j.prototype.reverse=function(){if(this.__filtered__){var t=new j(this);t.__dir__=-1,t.__filtered__=true}else t=this.clone(),t.__dir__*=-1;return t},j.prototype.value=function(){
var t,e=this.__wrapped__.value(),r=this.__dir__,n=ir(e),o=0>r,u=n?e.length:0;t=u;for(var i=this.__views__,a=0,c=-1,f=i.length;++c<f;){var _=i[c],s=_.size;switch(_.type){case"drop":a+=s;break;case"dropRight":t-=s;break;case"take":t=Le(t,a+s);break;case"takeRight":a=Be(a,t-s)}}if(t={start:a,end:t},i=t.start,a=t.end,t=a-i,o=o?a:i-1,i=this.__iteratees__,a=i.length,c=0,f=Le(t,this.__takeCount__),!n||200>u||u==t&&f==t)return H(e,this.__actions__);n=[];t:for(;t--&&f>c;){for(o+=r,u=-1,_=e[o];++u<a;){var l=i[u],s=l.type,l=(0,
l.iteratee)(_);if(2==s)_=l;else if(!l){if(1==s)continue t;break t}}n[c++]=_}return n},b.prototype.chain=function(){return gt(this)},b.prototype.commit=function(){return new d(this.value(),this.__chain__)},b.prototype.next=function(){this.__values__===Kt&&(this.__values__=Ct(this.value()));var t=this.__index__>=this.__values__.length,e=t?Kt:this.__values__[this.__index__++];return{done:t,value:e}},b.prototype.plant=function(t){for(var e,r=this;r instanceof g;){var n=yt(r);n.__index__=0,n.__values__=Kt,
e?o.__wrapped__=n:e=n;var o=n,r=r.__wrapped__}return o.__wrapped__=t,e},b.prototype.reverse=function(){var t=this.__wrapped__;return t instanceof j?(this.__actions__.length&&(t=new j(this)),t=t.reverse(),t.__actions__.push({func:dt,args:[bt],thisArg:Kt}),new d(t,this.__chain__)):this.thru(bt)},b.prototype.toJSON=b.prototype.valueOf=b.prototype.value=function(){return H(this.__wrapped__,this.__actions__)},Me&&(b.prototype[Me]=jt),(de||ge||{})._=b,typeof define=="function"&&typeof define.amd=="object"&&define.amd? define(function(){
return b}):ve&&be?(je&&((be.exports=b)._=b),ve._=b):me._=b}).call(this);
